vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       users:
           uri_prefix: /images/users
           upload_destination: '%kernel.project_dir%/public/images/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       articles:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       publications:
            uri_prefix: /images/publications
            upload_destination: '%kernel.project_dir%/public/images/publications'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
